Repository hmcts/am-judicial-booking-service, pull requests merged in 2021-10, with the labels that each got.

#86 Upgrade Azure RM and Terraform
  infrastructure/.terraform-version
  infrastructure/terraform.tf
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-86

#87 Add azuread provider config
  infrastructure/terraform.tf
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-87

#88 Fortify Scan fix for Judicial Service
  src/main/resources/application.yaml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-88

#90 Remove unwanted vars
  infrastructure/variables.tf
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-90
