Repository hmcts/am-judicial-booking-service, pull requests merged in 2022-03, with the labels that each got.

#205 ignore fortify scan failure
  Jenkinsfile_nightly
  build.gradle
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-205

#214 Updated the chart version
  charts/am-judicial-booking-service/Chart.yaml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-214

#206 LD load on startup based on yml flag
  build.gradle
  charts/am-judicial-booking-service/Chart.yaml
  charts/am-judicial-booking-service/values.yaml
  src/integrationTest/java/uk/gov/hmcts/reform/judicialbooking/controller/CreateBookingIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialbooking/controller/QueryBookingIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/config/LDDummyClient.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/config/LaunchDarklyConfiguration.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/launchdarkly/FeatureConditionEvaluation.java
  src/main/resources/application.yaml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-206

#217 Am 2066 java upgrade
  charts/am-judicial-booking-service/Chart.yaml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-217

#218 Fix CVE-2018-1258
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-218

#219 gradle upgrade to 7.4.1
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/integrationTest/java/uk/gov/hmcts/reform/judicialbooking/controller/BaseTest.java
  src/smokeTest/java/uk/gov/hmcts/reform/judicialbooking/BaseTest.java
  src/test/java/uk/gov/hmcts/reform/judicialbooking/util/JacksonUtilsTest.java
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-219

#225 Cve fix
  build.gradle
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-225

#230 CVE fix jackson Databind dependency
  build.gradle
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-230

#231 CVE fix lang-tag dependency
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-231
