Repository hmcts/am-judicial-booking-service, pull requests merged in 2022-09, with the labels that each got.

#437 AM-2343 Suppressing LD SnakeYaml CVE
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-437

#444 Suppress new versions of SnakeYaml CVE
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-444

#447 enable fta's in nightly build
  Jenkinsfile_nightly
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-447

#448 vault reading change
  Jenkinsfile_nightly
  build.gradle
  charts/am-judicial-booking-service/Chart.yaml
  charts/am-judicial-booking-service/values.preview.template.yaml
  charts/am-judicial-booking-service/values.yaml
  infrastructure/.terraform-version
  infrastructure/terraform.tf
  src/main/resources/application.yaml
  src/main/resources/bootstrap.yml
Labels: ns:am, prd:am, no-changes, rel:am-judicial-booking-service-pr-448

#453 nightly build changes
  Jenkinsfile_nightly
  security.sh
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-453

#454 nightly build changes
  audit.json
  security.sh
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-454

#455 Update audit.json
  audit.json
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-455

#456 Update audit.json
  audit.json
  security.sh
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-456

#463 Update audit.json
  audit.json
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-463

#470 Suppressing snakeyaml additional CVE
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-470
