Repository hmcts/am-judicial-booking-service, pull requests merged in 2022-10, with the labels that each got.

#478 Jackson CVE-2022-42003
  build.gradle
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-478

#498 Am build fix
  build.gradle
  docker/database/Dockerfile
  infrastructure/terraform.tf
Labels: ns:am, prd:am, no-changes, rel:am-judicial-booking-service-pr-498

#508 fortify fix
  docker/database/Dockerfile
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-508
