Repository hmcts/am-judicial-booking-service, pull requests merged in 2022-05, with the labels that each got.

#307 Update combine-prs.yml
  .github/workflows/combine-prs.yml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-307

#263 AM-2136: Upgrading to Java 17
  Dockerfile
  build.gradle
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-263

#313 Revert "AM-2136: Upgrading to Java 17"
  Dockerfile
  build.gradle
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-313

#314 Delete dependabot.yml
  .github/dependabot.yml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-314

#324 Spring update to 5.3.20
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-324

#315 FTA reports jdk17 suppression
  Dockerfile
  build.gradle
  src/test/java/uk/gov/hmcts/reform/judicialbooking/launchdarkly/FeatureConditionEvaluationTest.java
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-315
