Repository hmcts/am-judicial-booking-service, pull requests merged in 2022-02, with the labels that each got.

#182 Addressing sonar smells
  src/integrationTest/java/uk/gov/hmcts/reform/judicialbooking/controller/CreateBookingIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/controller/endpoints/CreateBookingController.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/domain/model/BookingResponse.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/util/JsonBConverter.java
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-182

#190 Updated tomcat-embed-core & tomcat-embed-websocket
  build.gradle
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-190

#191 jar bumps
  build.gradle
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-191

#199 New bumps
  build.gradle
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-199
