Repository hmcts/am-judicial-booking-service, pull requests merged in 2023-07, with the labels that each got.

#760 AM-2846: For preview pipelines enable cleanup of helm releases
  Jenkinsfile_CNP
Labels: ns:am, prd:am, keep-helm, rel:am-judicial-booking-service-pr-760

#751 AM-2823-CVE-2023-20883 FIX
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-751

#763 AM-2852 CVE-2023-34981 tomcat upgrade 9.0.76
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-763

#767 AM-2728 CVE-2022-1471 snakeyaml 2.0
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-767

#768 AM-2860 Remove Github Autoupdate
  .github/workflows/autoupdate.yml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-768

#759 AM-2842: Reduce amount of logging in App Insights for /health
  lib/applicationinsights.json
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-759

#766 AM-2851 CVE-2023-2976 WIP cve still showing guava@30.1-jre not sure how
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-766

#787 AM-2878 FTA report link missing in Master pipelines - publishHTML sec…
  Jenkinsfile_CNP
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-787

#788 AM-2883 CVE-2023-34035 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-788

#791 AM-2888 CVE-2023-34034 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-791
