Repository hmcts/am-judicial-booking-service, pull requests merged in 2023-08, with the labels that each got.

#797 AM-2888 CVE-2023-34035 spring-security upgraded 6.0.5
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-797

#798 AM-2888 CVE-2023-34034 Fix spring-security configured and downgraded …
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-798

#762 AM-2849: Retire obsolete controllers and associated tests after review
  src/integrationTest/java/uk/gov/hmcts/reform/judicialbooking/controller/DeleteBookingControllerIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialbooking/controller/SwaggerRedirectControllerIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialbooking/controller/WelcomeControllerIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/controller/S2SAuthentication.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/controller/SwaggerRedirectController.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/controller/endpoints/DeleteBookingController.java
  src/main/resources/application.yaml
  src/smokeTest/java/uk/gov/hmcts/reform/judicialbooking/SmokeTest.java
  src/test/java/uk/gov/hmcts/reform/judicialbooking/controller/S2SAuthenticationTest.java
  src/test/java/uk/gov/hmcts/reform/judicialbooking/controller/SwaggerRedirectControllerTest.java
  src/test/java/uk/gov/hmcts/reform/judicialbooking/controller/endpoints/DeleteBookingControllerTest.java
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-762

#808 AM-2998 Bump HMCTS Java-logging to v6+
  build.gradle
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-808

#809 AM-2908: Invalid validation on User IDs to accommodate Old Format of …
  src/main/java/uk/gov/hmcts/reform/judicialbooking/domain/service/BookingOrchestrator.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/domain/service/common/ParseRequestService.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/util/Constants.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/util/ValidationUtil.java
  src/test/java/uk/gov/hmcts/reform/judicialbooking/domain/service/BookingOrchestratorTest.java
  src/test/java/uk/gov/hmcts/reform/judicialbooking/domain/service/common/ParseRequestServiceTest.java
  src/test/java/uk/gov/hmcts/reform/judicialbooking/helper/TestDataBuilder.java
  src/test/java/uk/gov/hmcts/reform/judicialbooking/util/ValidationUtilTest.java
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-809

#820 AM-2909 Zap Security Scan Failing for V2 URL
  audit.json
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-820

#821 10112_Session Management Response Identified igonre added
  audit.json
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-821
