Repository hmcts/am-judicial-booking-service, pull requests merged in 2023-02, with the labels that each got.

#633 depenency check
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-633

#658 exception fix for LD flag
  src/integrationTest/java/uk/gov/hmcts/reform/judicialbooking/controller/CreateBookingIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialbooking/controller/QueryBookingIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/controller/advice/JudicialBookingControllerAdvice.java
  src/test/java/uk/gov/hmcts/reform/judicialbooking/controller/advice/JudicialBookingControllerAdviceTest.java
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-658

#669 JBS:Application Nightly build failed due to CVE-2022-45688
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-669
