Repository hmcts/am-judicial-booking-service, pull requests merged in 2023-05, with the labels that each got.

#725 AM-2786 CVE-2023-20873 AM-2787 CVE-2023-20862 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-725

#722 AM-2782 CVE-2021-22044 spring-cloud-starter-openfeign upgraded to 2.2…
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-722

#732 AM-2786 CVE-2023-20873 AM-2787 CVE-2023-20862
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-732

#718 AM-2750
  .gitignore
  Dockerfile
  build.gradle
  charts/am-judicial-booking-service/Chart.yaml
  charts/am-judicial-booking-service/values.preview.template.yaml
  charts/am-judicial-booking-service/values.yaml
  lib/AI-Agent.xml
  lib/applicationinsights-agent-2.4.1.jar
  lib/applicationinsights.json
  src/main/java/uk/gov/hmcts/reform/judicialbooking/config/AppInsightsConfig.java
  web.config
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-718

#744 DTSPO-13810 reschedule jenkins nightly builds
  Jenkinsfile_nightly
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-744

#745 nightly cron timing corrected
  Jenkinsfile_nightly
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-745

#740 AM-2768
  Jenkinsfile_CNP
  build.gradle
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-740

#737 AM-2792 Hide Unrequired Swagger Endpoints - @Hidden added
  src/main/java/uk/gov/hmcts/reform/judicialbooking/controller/S2SAuthentication.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/controller/WelcomeController.java
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-737

#738 Am 2793 publish swagger docs
  .github/workflows/swagger.yml
  README.md
  src/integrationTest/java/uk/gov/hmcts/reform/judicialbooking/config/SwaggerPublisher.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/controller/WelcomeController.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/controller/endpoints/CreateBookingController.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/controller/endpoints/QueryBookingController.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/util/Swagger2SpringBoot.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/judicialbooking/controller/WelcomeControllerTest.java
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-738

#748 AM-2816 CVE-2023-28709 tomcat upgraded to 9.0.74
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-748
