Repository hmcts/am-judicial-booking-service, pull requests merged in 2023-06, with the labels that each got.

#750 AM-2823-CVE-2023-20883 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-750

#758 AM-2839 CVE-2023-35116 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-758

#761 AM-2851 CVE-2023-2976 and AM-2852 CVE-2023-34981 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-761

#757 AM-2776 CVE-2023-20863 spring framework upgrade 5.3.27
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-757

#755 AM-2835: Configure arrays in FTAs so where possible they are unordered
  build.gradle
  src/functionalTest/resources/features/F-002/S-012.td.json
  src/functionalTest/resources/features/F-002/S-016.td.json
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-755
