Repository hmcts/am-judicial-booking-service, pull requests merged in 2023-04, with the labels that each got.

#708 Am 2520 cleanup suppressions
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-708

#710 AM-2740 CVE-2023-20861,CVE-2023-20860 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-710

#711 AM-2742 remove security.sh
  security.sh
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-711

#712 Revert "AM-2742 remove security.sh"
  security.sh
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-712

#720 AM-2776 CVE-2023-20863 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-720

#714 AM-2742 remove security.sh
  Jenkinsfile_nightly
  security.sh
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-714

#715 AM-2743
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  build.gradle
  src/functionalTest/resources/logback-test.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-715
