Repository hmcts/am-judicial-booking-service, pull requests merged in 2023-10, with the labels that each got.

#852 AM-2948 Temp disabling of Security Scan (Zap) in Nightly - Reenable
  Jenkinsfile_nightly
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-852

#859 AM-2958 Migrate to Workload Identity from aad-pod-identity - chart-ja…
  charts/am-judicial-booking-service/Chart.yaml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-859

#861 Am 2943 provision terraform postgres v15 demo 2
  infrastructure/main.tf
  infrastructure/terraform.tf
  infrastructure/variables.tf
Labels: ns:am, prd:am, add-or-update, rel:am-judicial-booking-service-pr-861

#863 Am 2943 provision terraform postgres v15 demo 2
  charts/am-judicial-booking-service/values.yaml
  infrastructure/main.tf
Labels: ns:am, prd:am, add-or-update, rel:am-judicial-booking-service-pr-863

#868 AM-2987 CVE-2023-42794, AM-2988 CVE-2023-42795, AM-2989 CVE-2023-4564…
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-868

#854 AM-3000: Update JBS query API validation to allow ORM service to bypass some validation
  src/contractTest/java/uk/gov/hmcts/reform/judicialbooking/ProviderTestConfiguration.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialbooking/controller/QueryBookingIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/domain/service/common/ParseRequestService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/judicialbooking/domain/service/common/ParseRequestServiceTest.java
Labels: ns:am, prd:am, no-changes, enable_keep_helm, rel:am-judicial-booking-service-pr-854

#880 AM-3014 Resolve Sonar issues recently flagged on existing code in JBS…
  src/main/java/uk/gov/hmcts/reform/judicialbooking/controller/endpoints/DeleteBookingController.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/launchdarkly/FeatureConditionEvaluation.java
  src/test/java/uk/gov/hmcts/reform/judicialbooking/launchdarkly/FeatureConditionEvaluationTest.java
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-880

#881 Am 2943 Provision Pg v15 Demo User Host Secrets
  infrastructure/main.tf
  infrastructure/terraform.tf
  infrastructure/variables.tf
Labels: ns:am, prd:am, add-or-update, rel:am-judicial-booking-service-pr-881

#882 Am 2974 provision terraform postgres v15 ithc
  infrastructure/main.tf
  infrastructure/terraform.tf
  infrastructure/variables.tf
Labels: ns:am, prd:am, add-or-update, rel:am-judicial-booking-service-pr-882
