Repository hmcts/am-judicial-booking-service, pull requests merged in 2024-03, with the labels that each got.

#965 AM-3059 v15 Reader User Trigger 2 AAT, ITHC, Perftest, Demo
  infrastructure/main.tf
Labels: ns:am, prd:am, destroy, rel:am-judicial-booking-service-pr-965

#1009 Adding kv_subscription var and setting for aat
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:am, prd:am, destroy, rel:am-judicial-booking-service-pr-1009

#1011 AM-3023 Schema Trigger bumped to 2
  infrastructure/main.tf
Labels: ns:am, prd:am, destroy, rel:am-judicial-booking-service-pr-1011

#1012 AM-3059 v15 Reader User Trigger AAT 4, ITHC, Perftest, Demo
  infrastructure/main.tf
Labels: ns:am, prd:am, destroy, rel:am-judicial-booking-service-pr-1012

#1015 AM-3023 Migrate Data JBS AAT - Schema Trigger bumped to 3
  infrastructure/main.tf
Labels: ns:am, prd:am, destroy, rel:am-judicial-booking-service-pr-1015

#1021 AM-3059 v15 Reader User Trigger 5 AAT, ITHC, Perftest, Demo
  infrastructure/main.tf
Labels: ns:am, prd:am, destroy, rel:am-judicial-booking-service-pr-1021

#966 AM-3116 Update AAT Chart for Staging JBS
  charts/am-judicial-booking-service/values.aat.template.yaml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-966
