Repository hmcts/am-judicial-booking-service, pull requests merged in 2024-11, with the labels that each got.

#1186 Revert "DTSAM-578 CVE-2024-9329 glassfish Suppression"
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-1186

#1188 DTSAM-602 CVE-2024-38820 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-1188

#1166 DTSAM-569 adjust multiple user FTA
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  src/functionalTest/resources/features/F-001/S-004.td.json
  src/functionalTest/resources/features/F-002/F-002.feature
  src/functionalTest/resources/features/F-002/S-012.td.json
  src/functionalTest/resources/features/F-002/S-016.td.json
  src/functionalTest/resources/features/F-002/S-017.td.json
  src/functionalTest/resources/features/common/CreationBaseDataForBooking.td.json
  src/functionalTest/resources/features/common/CreationBaseDataForBookingBeftaUser.td.json
  src/functionalTest/resources/features/common/CreationBaseDataForBookingBeftaUser1.td.json
  src/functionalTest/resources/features/common/CreationBaseDataForBookingBeftaUser2.td.json
  src/functionalTest/resources/features/common/DeleteDataForBookingsBeftaUser.td.json
  src/functionalTest/resources/features/common/DeleteDataForBookingsBeftaUser1.td.json
  src/functionalTest/resources/features/common/DeleteDataForBookingsBeftaUser2.td.json
  src/functionalTest/resources/features/common/UnprocessableEntityResponse.td.json
  src/functionalTest/resources/features/common/users/BeftaUser2.td.json
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-1166
