Repository hmcts/am-judicial-booking-service, pull requests merged in 2025-06, with the labels that each got.

#1287 DTSAM-913 Fortify client to Upgrade to from 1.4.8 to 1.4.9
  build.gradle
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-1287

#1288 DTSAM-920 CVE-2025-48734 Detail apache common Suppress
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-judicial-booking-service-pr-1288

#1058 CME-58: Spring Boot 3 Upgrade and Java 21 Upgrade JBS
  .github/workflows/swagger.yml
  .gitignore
  Dockerfile
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/OrgRoleMappingRefreshConsumerTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/judicialbooking/befta/JudicialBookingEntityApiBeftaRunner.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialbooking/config/SwaggerPublisher.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialbooking/controller/BaseTestIntegration.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialbooking/controller/CreateBookingIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialbooking/controller/QueryBookingIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/judicialbooking/controller/SwaggerRedirectControllerIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/JudicialBookingApplication.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/apihelper/ApiOriginFilter.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/config/ApplicationConfiguration.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/config/AuthCheckerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/config/CacheConfig.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/config/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/config/SecurityEndpointFilter.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/controller/SwaggerRedirectController.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/controller/advice/JudicialBookingControllerAdvice.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/controller/endpoints/CreateBookingController.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/controller/endpoints/QueryBookingController.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/data/BookingEntity.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/domain/model/JudicialRefreshRequest.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/util/CorrelationInterceptorUtil.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/util/JacksonUtils.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/util/JsonBConverter.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/util/SecurityUtils.java
  src/main/java/uk/gov/hmcts/reform/judicialbooking/util/ValidationUtil.java
  src/main/resources/application.yaml
  src/smokeTest/java/uk/gov/hmcts/reform/judicialbooking/BaseTest.java
  src/smokeTest/java/uk/gov/hmcts/reform/judicialbooking/SmokeTest.java
  src/test/java/uk/gov/hmcts/reform/judicialbooking/controller/SwaggerRedirectControllerTest.java
  src/test/java/uk/gov/hmcts/reform/judicialbooking/controller/advice/JudicialBookingControllerAdviceTest.java
  src/test/java/uk/gov/hmcts/reform/judicialbooking/domain/service/BookingOrchestratorTest.java
  src/test/java/uk/gov/hmcts/reform/judicialbooking/oidc/IdamRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/judicialbooking/oidc/JwtGrantedAuthoritiesConverterTest.java
  src/test/java/uk/gov/hmcts/reform/judicialbooking/util/CorrelationInterceptorUtilTest.java
  src/test/java/uk/gov/hmcts/reform/judicialbooking/util/JacksonUtilsTest.java
  src/test/java/uk/gov/hmcts/reform/judicialbooking/util/JsonBConverterTest.java
  src/test/java/uk/gov/hmcts/reform/judicialbooking/util/SecurityUtilsTest.java
Labels: ns:am, prd:am, aat/no-changes, prod/no-changes, rel:am-judicial-booking-service-pr-1058
